version: '3.6'

services:
 nginx:
  build:
    context: .
    dockerfile: docker/nginx.dockerfile
  volumes:
    - ./src:/var/www/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./logs/nginx:/var/log/nginx
  ports:   
  - 80:80  
  depends_on:
   - php
 php:
  build:
    context: .
    dockerfile: docker/php.dockerfile
  volumes:
    - ./src:/var/www/html:cached
    - ./logs/fpm:/var/log
 mysql:
  image: mysql:latest
  restart: always
  env_file:
    - ./mysql/.env
  volumes:
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./logs/mysql:/var/log
  ports:
    - "3306:3306"
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   PMA_HOST: mysql
   PMA_ARBITRARY: 1
  restart: always
  ports:
   - 81:80
  depends_on:
   - mysql
 composer:
  image: composer:latest
  working_dir: /var/www/html
  entrypoint: ["composer","--ignore-platform-reqs"]
  volumes:
    - ./src:/var/www/html 
 artisan:
  build:
    context: .
    dockerfile: docker/php.dockerfile
  volumes:
     - ./src:/var/www/html
  entrypoint: ["php", "/var/www/html/artisan"]
 npm:
  image: node:14
  working_dir: /var/www/html
  entrypoint: ['npm']
  volumes:
   - ./src:/var/www/html

